DROP TABLE WALLET;
DROP TABLE RERULE;
DROP TABLE RRRULE;
DROP TABLE REWARDTYPE;
DROP TABLE ACTIVITYTYPE;
DROP TABLE BRAND;
DROP TABLE CUSTOMER;
DROP TABLE USERS;

CREATE TABLE USERS(
    USERID VARCHAR2(50),
    PASSWORD VARCHAR2(30) NOT NULL,
    USERTYPE CHAR(1) NOT NULL,
    CONSTRAINT pk_users primary key(USERID)
);

CREATE TABLE CUSTOMER(
	CUSTOMERID VARCHAR2(50),
	FNAME VARCHAR2(50) NOT NULL,
    LNAME VARCHAR2(50),
	PHONENUMBER VARCHAR2(10),
	ADDRESS VARCHAR2(80),
	CONSTRAINT pk_customer primary key(CUSTOMERID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY(CUSTOMERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);


CREATE TABLE BRAND(
BID VARCHAR2(50),
BNAME VARCHAR(80) NOT NULL,
ADDRESS VARCHAR(80),
JOINDATE DATE NOT NULL,
CONSTRAINT PK_BRAND primary key(BID),
CONSTRAINT FK_BRAND FOREIGN KEY (BID) REFERENCES Users(USERID)
ON DELETE CASCADE
);



CREATE TABLE ACTIVITYTYPE(
	ACTIVITYCODE VARCHAR2(10),
	ACTIVITYNAME VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_activity primary key(ACTIVITYCODE)
);



CREATE TABLE REWARDTYPE(
	REWARDCODE  VARCHAR2(10),
	REWARDNAME VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_rewards primary key(REWARDCODE)
);



CREATE TABLE RRRULE(
RRCODE VARCHAR2(10),
VERSIONNO NUMBER(5),
POINTS NUMBER(10),
REWARDCODE VARCHAR2(10),
CONSTRAINT PK_RRRULE primary key(RRCODE, VERSIONNO),
CONSTRAINT FK_RRCODE FOREIGN KEY (REWARDCODE) REFERENCES REWARDTYPE(REWARDCODE)
);



CREATE TABLE RERULE(
RECODE VARCHAR2(10),
VERSIONNO NUMBER(5),
POINTS NUMBER(10),
ACTIVITYCODE VARCHAR2(10),
CONSTRAINT PK_RERULE primary key(RECODE, VERSIONNO),
CONSTRAINT FK_ACTIVITYCODE_RE FOREIGN KEY (ACTIVITYCODE) REFERENCES ACTIVITYTYPE(ACTIVITYCODE)
);


CREATE TABLE LOYALTYPROGRAM(
	--NEEDS ATTENTION
	LPCODE VARCHAR2(10),
	LPNAME VARCHAR2(30),
	ACTIVITYCODE VARCHAR2(10),
	REWARDCODE VARCHAR2(10),
	RECODE VARCHAR2(10) NOT NULL,
	REVERSION NUMBER(5),
	RRRODE VARCHAR2(10) NOT NULL,
	RRVERSION NUMBER (5),
	CONSTRAINT PK_LP PRIMARY KEY(LPCODE),
	CONSTRAINT FK_LPACT FOREIGN KEY ACTIVITYCODE REFERENCES ACTIVITYTYPE(ACTIVITYCODE),
	CONSTRAINT FK_LPREW FOREIGN KEY REWARDCODE REFERENCES REWARDTYPE(REWARDCODE)
	--CONSTRAINT FK_LP_RE FOREIGN KEY 
);


CREATE TABLE REGULAR(
	--NEEDS ATTENTION
	REGPROGID NUMBER(10),
	LPCODE VARCHAR2(10),
	CONSTRAINT PK_REG PRIMARY KEY(REGPROGID),
	CONSTRAINT FK_REG FOREIGN KEY (LPCODE) REFERENCES LOYALTYPROGRAM(LPCODE)
);

CREATE TABLE TIER(
	--NOT COMPLETE
	POINTS NUMBER(5),
);


CREATE TABLE WALLET(
	WALLETID VARCHAR2(4),
	POINTSEARNED FLOAT(10),
	DATEOFACTIVITY DATE,
	CUSTOMERID VARCHAR2(50),
	CONSTRAINT pk_wallet primary key(WALLETID),
	CONSTRAINT fk_customerwallet FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);

CREATE TABLE REVIEW(
	REVIEWID NUMBER(4),
	REVIEWTEXT VARCHAR2(200),
	CUSTOMERID NUMBER(10),
	CONSTRAINT PK_REVIEW PRIMARY KEY(REVIEWID),
	CONSTRAINT FK_REVIEW FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);

CREATE TABLE GIFTCARD(
	GCID VARCHAR2(4),
	GCNAME VARCHAR2(30),
	CAPACITY NUMBER(5) NOT NULL,
	EXPIRY DATE NOT NULL,
	CONSTRAINT PK_REVIEW PRIMARY KEY (GCID) 	
);

CREATE TABLE FREEPRODUCT(
	FPRODID VARCHAR2(4),
	FPRODNAME VARCHAR2(30),
	CAPACITY NUMBER (5) NOT NULL,
	CONSTRAINT PK_FPROD PRIMARY KEY (FPRODID)
);

/*

CREATE TABLE Address(
AddressId  NUMBER(10),
stName VARCHAR(50),
aptNo VARCHAR(20),
city VARCHAR(50),
stateName CHAR(2),
zip NUMBER(5),
CONSTRAINT pk_address primary key(AddressId)
);
*/

/*  Admin table not necessary
CREATE TABLE ADMIN(
	ADMINID NUMBER(10),
	FNAME VARCHAR2(50),
    LNAME VARCHAR2(50),
	PHONENUMBER NUMBER(10),
    ADDRESS VARCHAR2(80),
    USERID VARCHAR2(50),
	CONSTRAINT pk_admin primary key(ADMINID),
    CONSTRAINT FK_ADMIN FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);*/





-----------------------------------Stored Procedures-----------------------------------------------

-- Adding a brand into marketplace by admin
CREATE or REPLACE PROCEDURE admin_add_brand
(
    brandId IN VARCHAR2,
    brandName IN VARCHAR2,
    brandAddress IN VARCHAR2,
    ret OUT INT
) 
AS
OLDUSERIDCNT INT;
JOIN_DATE DATE;
BEGIN
    SELECT COUNT(USERID) INTO OLDUSERIDCNT FROM USERS WHERE USERID = brandId;

    IF OLDUSERIDCNT > 0 THEN
        ret := 0;
    ELSE
        SELECT CURRENT_DATE INTO JOIN_DATE FROM DUAL;
        -- Insert into users table
        INSERT INTO USERS(USERID, PASSWORD, USERTYPE) VALUES(brandId, '1234', 'B');
        -- Insert into brand table
        INSERT INTO BRAND(BID, BNAME, ADDRESS, JOINDATE) VALUES(brandId, brandName, brandAddress, JOIN_DATE);

        ret := 1;
    END IF;    
END;
/

-- Adding a customer into marketplace by admin
CREATE or REPLACE PROCEDURE admin_add_customer
(
    customerId IN VARCHAR2,
    customerFName IN VARCHAR2,
    customerLName IN VARCHAR2,
    customerPhoneNumber IN VARCHAR2,
    customerAddress IN VARCHAR2, 
    ret OUT INT
) 
AS
OLDUSERIDCNT INT;
BEGIN
    SELECT COUNT(USERID) INTO OLDUSERIDCNT FROM USERS WHERE USERID = customerId;
    IF OLDUSERIDCNT > 0 THEN
        ret := 0;
    ELSE
        -- Insert into users table
        INSERT INTO USERS(USERID, PASSWORD, USERTYPE) VALUES(customerId, '1234', 'C');
        -- Insert into customer table
        INSERT INTO CUSTOMER(CUSTOMERID, FNAME, LNAME, PHONENUMBER, ADDRESS) VALUES(customerId, customerFName, customerLName, customerPhoneNumber, customerAddress);

        ret := 1;
    END IF;    
END;
/