DROP TABLE WALLET;
DROP TABLE RERULES;
DROP TABLE RRRULES;
DROP TABLE REWARD_TYPE;
DROP TABLE ACTIVITY_TYPE;
DROP TABLE BRANDS;
/*DROP TABLE ADMIN;*/
DROP TABLE CUSTOMER;
DROP TABLE USERS;

CREATE TABLE USERS(
    USERID VARCHAR2(50),
    PASSWORD VARCHAR2(30) NOT NULL,
    USERTYPE CHAR(1) NOT NULL,
    CONSTRAINT pk_users primary key(USERID)
);

CREATE TABLE CUSTOMER(
	CUSTOMERID VARCHAR2(50),
	FNAME VARCHAR2(50),
  LNAME VARCHAR2(50),
	PHONENUMBER NUMBER(10),
	ADDRESS VARCHAR2(80),
	CONSTRAINT pk_customer primary key(CUSTOMERID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY(CUSTOMERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);


CREATE TABLE Brands(
BID VARCHAR2(50),
BNAME VARCHAR(80),
ADDRESS VARCHAR(80),
JOINDATE DATE,
CONSTRAINT PK_BRAND primary key(bId),
CONSTRAINT FK_BRAND FOREIGN KEY (bId) REFERENCES Users(UserID)
ON DELETE CASCADE
);



CREATE TABLE ACTIVITY_TYPE(
	ACTIVITYCODE VARCHAR2(10),
	ACTIVITYNAME CHAR (50),
	CONSTRAINT pk_activity primary key(ACTIVITYCODE)
);



CREATE TABLE REWARD_TYPE(
	REWARDCODE  VARCHAR2(10),
	REWARDNAME CHAR(50),
	CONSTRAINT pk_rewards primary key(REWARDCODE)
);



CREATE TABLE RRRULES(
RRCODE VARCHAR2(10),
VERSIONNO NUMBER(5),
POINTS NUMBER(10),
REWARDCODE VARCHAR2(10),
CONSTRAINT PK_RRRULES primary key(RRCODE, VERSIONNO),
CONSTRAINT FK_RRCODE FOREIGN KEY (REWARDCODE) REFERENCES REWARD_TYPE(REWARDCODE)
);



CREATE TABLE RERULES(
RECODE VARCHAR2(10),
VERSIONNO NUMBER(5),
POINTS NUMBER(10),
ACTIVITYCODE VARCHAR2(10),
CONSTRAINT PK_RERULES primary key(RECODE, VERSIONNO),
CONSTRAINT FK_ACTIVITYCODE_RE FOREIGN KEY (ACTIVITYCODE) REFERENCES ACTIVITY_TYPE(ACTIVITYCODE)
);


CREATE TABLE LOYALTYPROGRAM(
	--NEEDS ATTENTION
	LPCODE VARCHAR2(10),
	LPNAME VARCHAR2(30),
	ACTIVITYCODE VARCHAR2(10),
	REWARDCODE VARCHAR2(10),
	RECODE VARCHAR2(10) NOT NULL,
	REVERSION NUMBER(5),
	RRRODE VARCHAR2(10) NOT NULL,
	RRVERSION NUMBER (5),
	CONSTRAINT PK_LP PRIMARY KEY(LPCODE),
	CONSTRAINT FK_LPACT FOREIGN KEY ACTIVITYCODE REFERENCES ACTIVITY_TYPE(ACTIVITYCODE),
	CONSTRAINT FK_LPREW FOREIGN KEY REWARDCODE REFERENCES REWARD_TYPE(REWARDCODE)
	--CONSTRAINT FK_LP_RE FOREIGN KEY 
);


CREATE TABLE REGULAR(
	--NEEDS ATTENTION
	REGPROGID NUMBER(10),
	LPCODE VARCHAR2(10),
	CONSTRAINT PK_REG PRIMARY KEY(REGPROGID),
	CONSTRAINT FK_REG FOREIGN KEY (LPCODE) REFERENCES LOYALTYPROGRAM(LPCODE)
);

CREATE TABLE TIER(
	--NOT COMPLETE
	POINTS NUMBER(5),
);


CREATE TABLE WALLET(
	WALLETID VARCHAR2(4),
	POINTSEARNED FLOAT(10),
	DATEOFACTIVITY DATE,
	CUSTOMERID VARCHAR2(50),
	CONSTRAINT pk_wallet primary key(WALLETID),
	CONSTRAINT fk_customerwallet FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);

CREATE TABLE REVIEW(
	REVIEWID NUMBER(4),
	REVIEWTEXT VARCHAR2(200),
	CUSTOMERID NUMBER(10),
	CONSTRAINT PK_REVIEW PRIMARY KEY(REVIEWID),
	CONSTRAINT FK_REVIEW FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);

CREATE TABLE GIFTCARD(
	GCID VARCHAR2(4),
	GCNAME VARCHAR2(30),
	CAPACITY NUMBER(5) NOT NULL,
	EXPIRY DATE NOT NULL,
	CONSTRAINT PK_REVIEW PRIMARY KEY (GCID) 	
);

CREATE TABLE FREEPRODUCT(
	FPRODID VARCHAR2(4),
	FPRODNAME VARCHAR2(30),
	CAPACITY NUMBER (5) NOT NULL,
	CONSTRAINT PK_FPROD PRIMARY KEY (FPRODID)
);

/*

CREATE TABLE Address(
AddressId  NUMBER(10),
stName VARCHAR(50),
aptNo VARCHAR(20),
city VARCHAR(50),
stateName CHAR(2),
zip NUMBER(5),
CONSTRAINT pk_address primary key(AddressId)
);
*/

/*  Admin table not necessary
CREATE TABLE ADMIN(
	ADMINID NUMBER(10),
	FNAME VARCHAR2(50),
    LNAME VARCHAR2(50),
	PHONENUMBER NUMBER(10),
    ADDRESS VARCHAR2(80),
    USERID VARCHAR2(50),
	CONSTRAINT pk_admin primary key(ADMINID),
    CONSTRAINT FK_ADMIN FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
);*/
